# files
layouts: ./_/layouts
destination: ./_/site
sass:
  sass_dir: ./_/sass

# Markdown
highlighter: pygments
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true

# Site settings
permalink: /:title.html
exclude: ["Makefile", "README.md", "_/Gemfile", "_/Gemfile.lock",  "CNAME"]

# Site info
meta:
  title: Rico Sta. Cruz
  author: Rico Sta. Cruz
  name: Rico Sta. Cruz TIL
  hostname: ricostacruz.com

facebook:
  app_id: 169204529787544
  admin: ricostacruz

analytics:
  id: "UA-20473929-1"

defaults:
  - scope:
      path: ""
    values:
      layout: "article"
      tags: []
